import { CheckCircle, UserCheck } from 'lucide-react'
import { useState } from 'react'
import { postJSON } from '../api/client'

interface Props {
  planId: string
  onApproved: () => void
}

export default function HITLApprovalGate({ planId, onApproved }: Props) {
  const [approving, setApproving] = useState(false)
  const [approved, setApproved] = useState(false)

  async function handleApprove() {
    setApproving(true)
    try {
      await postJSON('/plans/approve', { plan_id: planId, approved_by: 'human' })
      setApproved(true)
      onApproved()
    } catch {
      setApproving(false)
    }
  }

  if (approved) {
    return (
      <div className="flex items-center gap-2 bg-green-50 border border-green-200 rounded px-4 py-3 text-sm text-green-700">
        <CheckCircle size={16} />
        Plan approved and published. Human oversight complete.
      </div>
    )
  }

  return (
    <div className="bg-amber-50 border border-amber-300 rounded p-4 space-y-3">
      <div className="flex items-center gap-2 text-amber-800 font-semibold text-sm">
        <UserCheck size={16} />
        Human review required before this plan is published
      </div>
      <p className="text-xs text-amber-700">
        This study plan was generated by AI. Review the Critic objections and plan content
        before approving. Once approved, the plan becomes active.
      </p>
      <p className="text-xs text-amber-600 font-mono">Plan ID: {planId}</p>
      <button
        onClick={handleApprove}
        disabled={approving}
        className="bg-amber-600 hover:bg-amber-700 text-white text-sm px-4 py-2 rounded font-medium disabled:opacity-50 transition"
      >
        {approving ? 'Approving…' : '✓ Approve & Publish Plan'}
      </button>
    </div>
  )
}
